cloudbees/jenkins-scripts

- dump-copy-move-error-history.groovy
Dump all the history logs of failed Move/Copy/Promote operations in a file
@reviewbybees
> Dump Copy/Move/Promote Error History script.

- ucStoreAndPromoteWithDependencies.groovy
@cloudbees/team-support @duemir 
A script to calculate dependencies of a plugin in a Custom Update Center. It fills a collection of required dependencies. 
The collection can be used to either automatically store a plugin and its dependencies OR promote a plugin and its dependencies.
But doing both is not a good idea. The download tasks are actually Queue.Tasks that are scheduled immediately. So **we would have to wait for all download tasks to finish before launching the promote**...
Maybe we can add a field to decide whether we want to STORE or PROMOTE:
```
if(action == "STORE") {
downloadPlugins(myUC, requiredDeps.values())
} else if (action == "PROMOTE") {
promotePlugins(myUC, requiredDeps.values())
}
```
Or really code something that wait for the completion of download tasks to …
> [CE-672] Scripts to find, store, promote a plugin with its dependencies

- get-lastlogin-users.groovy
Without this import `import hudson.model.User`, we have an exception on `User.getAll()`
> Fix missing  import

- builds-running-more-than-24h.groovy
Simple script to get running builds that have been running for more than 24hours
> CE-3208 Script to get builds running for more than 24hrs

- setOrgFolderIndex.groovy
Fix the argument for the `setInterval` function in the `setOrgFolderIndex` script. This should be `folder` and not `interval`. The interval is already provided inside of the function.
> Fix argument for setInterval function

- license-upgrade/apply-license.groovy
In CJOC environment, list masters that need upgrading when incompatible masters have been found. Example output:
```
apply-license.groovy running...
Checks the license server for the new license, and if available, installs the license.
Determine the instance type: Operations Center
One or more masters have an incompatible version of cloudbees-license plugin. Please update them:
* old-mm-2
```
> List masters that need upgrading

- createManagedMasterK8s.groovy
- createTeamMasterK8s.groovy
[CE-4779](https://cloudbees.atlassian.net/browse/CE-4779): The KubernetesImagePullSecret only has a [default constructor](https://github.com/cloudbees/cloud-platform-master-provisioning-plugin/blob/master-provisioning-parent-2.5.2/master-provisioning-kubernetes/src/main/java/com/cloudbees/masterprovisioning/kubernetes/KubernetesImagePullSecret.java#L33-L35)
> [CE-4779] Fix example for KubernetesImagePullSecret

- credentials-migration/README.md
- credentials-migration/export-credentials-folder-level.groovy
- credentials-migration/export-credentials-system-level.groovy
- credentials-migration/update-credentials-folder-level.groovy
- credentials-migration/update-credentials-system-level.groovy
The following scripts are intended to help users to update their credentials in the new Jenkins Master when a Monholitic master is splitted.
These scripts are based on https://github.com/cloudbees/cloudbees-examples/tree/master/cloudbees-ci/cje-to-ci-migration-examples/CredentialsMigration. The reason why I am modifying them is that those scripts were mainly created to migrate credentials at the Operations Center level (it is expected not to have any credentials in any master), but in this use case, we are migrating credentials at Master level since we are splitting a Master.
These scripts not only migrate the credentials at the root/system level, but also at the folder level.
I test it with 500 username/password credentials + 500 ssh credentials type and it worked. I guess there is a …
> [CE-5455] Credentials migration scripts

- setCjocSecurity.groovy
This script will set the Security Setting Enforcement to Single Sign-On (security realm and authorization strategy)
The authentication mapping can be changed from RestrictedEquivalentRAMF to either TrustedEquivalentRAMF
or UntrustedEquivalentRAMF
It will also enforce all the security policies such as preventing XSS
> enforce SSO security realm with setCjocSecurity.groovy

- credentials-migration/update-credentials-folder-level.groovy
- credentials-migration/update-credentials-system-level.groovy
Some clients that have a large number of credentials on their controller, or many ssh credentials, can exceed the groovy string limit of 65535, and the credential import will fail.
If we save the encoded value to a file and load that file using the `File` class, it works around this limitation, and allows me to import the credentials.
> Credential import can exceed groovy string limit of 65535

- createManagedMasterK8s.groovy
The token is considered null if it is set after the bundle.
> The token is null if it is set after the bundle

- uc-certificate-fix/ucCertRemediation.groovy
The error due to https://support.cloudbees.com/hc/en-us/articles/4408359898011 does not go away right after you run this script. Either you can wait for the next periodic plugin update site check, or you can go to "Manage Jenkins" -> "Manage  Plugins" and scale the text small enough to be able to click the ‘check now’ button.
This PR is to make it so the update center data is refreshed after the offline update site has been removed, so the error will be gone from "Manage Jenkins" -> "Manage  Plugins" after running the script.
Tested with CloudBees CI on Traditional Platforms Client Controller 2.303.2.5
> automatically refresh update center data to clear the error under "Manage Plugins" without manual steps

- uc-certificate-fix/ucCertRemediation.groovy
Without this fix, when running the script on CloudBees CI on Modern Cloud Platforms it will fail to find the offline update center:
```
INFO: default offline updatecenter was not found, if this is not expected you may need to increase the value for _retry_time
Default offline UC was not found, if this was not expected you may need to increase "_retry_time"
```
After this fix, running this script (system clock is set to the correct time, Oct 18th) results in:
```
INFO: Executing remediation check [v00003]
INFO: Running bootstrap install, disabling retry interval
INFO: Checking if certificate validation is already disabled
INFO: Checking offline update center certificates...
INFO: Offline update center is ok, no update needed
INFO: /var/jenkins_home/init.groovy.d/ucCertRemediation.groovy …
```
> Add the offline update center path for CloudBees CI on Modern Cloud Platforms

- uc-certificate-fix/ucCertRemediation.groovy
The script for https://support.cloudbees.com/hc/en-us/articles/4408359898011 does not emit an obvious success or error message, so I'm updating it to be more clear if  action is required after the script is run.
Also, I've made it clear that if the script happens to fail, debug mode should be enabled and they should reach out to CloudBees  Support with the output.
> make the result of the script more understandable (either SUCCESS or ERROR)

- credentials-migration/update-credentials-folder-level.groovy
- credentials-migration/update-credentials-system-level.groovy
When working with a client migrating credentials from an operations center version [2.164.3.2 to 2.289.1.2](https://docs.cloudbees.com/docs/release-notes/latest/cloudbees-ci/), we found that if the credentials did not already exist on the target operations center, the credentials would not be created.
This new code checks the return code from [updateCredentials()](https://javadoc.jenkins.io/plugin/credentials/com/cloudbees/plugins/credentials/CredentialsStore.html#updateCredentials-com.cloudbees.plugins.credentials.domains.Domain-com.cloudbees.plugins.credentials.Credentials-com.cloudbees.plugins.credentials.Credentials-) and if that fails, it will call [addCredentials()](https://javadoc.jenkins.io/plugin/credentials/com/cloudbees/plugins/credentials/CredentialsStore.html#addCredentials-co …
> [CE-6555] Credential migration: Add error checking and account for credentials not already existing

- pruneOldSamlUsers.groovy
The script checks the users who have not logged in for a certain number of days and deletes them if the DELETE_USERS
flag is set to true. This is to prune users that get created automatically on SAML login, but are never deleted.
The script defines two constants:
- DAYS_SINCE_LOGIN is the number of days since a user has last logged in that determines if their account is deleted.
- DELETE_USERS is a boolean flag indicating whether or not to actually delete the users.
The script  loops through all the user accounts and checks if the user has a valid SAML login.
If a user has a valid login, it checks the last login timestamp to see if it is older than the last valid date. 
If it is, it adds the user ID to a list of deleted users
> Add script to prune old SAML SSO created users

- UpdateLivenessReadiness.groovy
Updates script from https://github.com/cloudbees/jenkins-scripts/pull/226 to more clearly log output and changes when multiple controllers exist. Prior to this change, the output would say it's updating multiple controllers, when in fact it's only updating one.
> update UpdateLivenessReadiness messages when multiple controllers exist

- webhooks-reregister-github.groovy
This script is used to re-register webhooks for all GitHub repositories in Jenkins, while keeping only one webhook for github organizations.
It first enables webhook management for all GitHub servers, then re-registers webhooks
for multibranch projects not in a Github organization, then disables webhook management
and re-registers webhooks for all Github organization folders.
It is done this way to avoid re-registering webhooks in all repositories AND at the Org level of a github org.
This is because the GitHub plugin will automatically register webhooks for all repositories in an org
when a webhook is registered at the org level, if the webhook management option is enabled.
> Add script to re-register github organizations and standalone multibranch webhooks

- pom.xml
As `master-provisioning-kubernetes` was integrated to OC monorepo:
* moved from `com.cloudbees.tiger.plugins` groupId to `com.cloudbees.operations-center.common`
* aligned with `operations-center` version
> [BEE-35262] Relocate master-provisioning-kubernetes

- cli-disable-enable/README.md
- cli-disable-enable/cli-toggle-disable-permanent.groovy
- cli-disable-enable/cli-toggle-disable.groovy
- cli-disable-enable/cli-toggle-enable.groovy
These scripts allow to disable the CLI while the Controller is running, and to reenable it again if needed for a temporary need, and then disable again.
> Scripts to disable and reenable CLI without a restart.

- credentials-migration/README.md
- credentials-migration/export-credentials-folder-level.groovy
- credentials-migration/export-credentials-system-level.groovy
- credentials-migration/update-credentials-folder-level.groovy
- credentials-migration/update-credentials-system-level.groovy
- pom.xml
Credential migration scripts are updated to support the "Secret file" credential type. Should also improve support of any credential type that relies on "SecretBytes" instead of "Secret".
Trilead's Base64 utility is replaced with Java standard library implementation.
> [SECO-4138] Add support of "Secret file" credential

- credentials-migration/export-credentials-folder-level.groovy
- credentials-migration/export-credentials-system-level.groovy
- credentials-migration/update-credentials-folder-level.groovy
- credentials-migration/update-credentials-system-level.groovy
Add examples of writing output to a local file for credentials migration.
> [SECO-4138] Add practical example to export encoded credentials to a file
