- folder-remove-healthmetrics.groovy
> add script to disable folder metrics

- github-enterprise-api-endpoint.groovy
Allows preconfiguring API endpoint for GitHub Enterprise.
> added github-enterprise-api-endpoint.groovy script

- updateJobs-fromTemplateA2TemplateB.groovy
It finds all the jobs in CJE instance with  a "Template_A"  and then update them to "Template_B"
@reviewbybees
> Update jobs from Template A to Template B

- updateJobs-fromTemplateA2TemplateB.groovy
update according to jglick's comments, plus controlling that the template name to update to is actually included within the Model List of the instance
> updateJobs-fromTemplateA2TemplateB  - version 2

- copyGrpsBetweenFolders.groovy
- copyRestrictionsBetweenFolders.groovy
- copyRestrictionsBetweenFolders2.groovy
> Copy groups or restrictions between folders

- FindAllGroupsInFolders.groovy
> list all groups in each folder

- listNamesMachinesVmwarePool.groovy
> list machine names from a vmware configuration

- RBAC_Example.groovy
> POC of how to list/manipulate RBAC entities from groovy

- get-current-queue-state.groovy
- move-copy-promote-simulation.groovy
@reviewbybees Scripts used to troubleshoot move/copy/promote issues. Inspired by @escoem
> Move copy promote simulate

- listMembersOfaJobGroups.groovy
> list member of groups assigned to a job

- createAgentsScript.groovy
- deleteAgents.groovy
- disableAgents.groovy
Scripts for :
create an script to create Agents from a Jenkins instance
disable agents on a Jenkins instance
delete agents on a Jenkins instance
> Some scripts related with Agents and Shared Agents

- schedule-templatized-jobs.groovy
Schedule all Jobs based on a specific template with few parameters such as quiet period, throttleLimit and sleep interval.
@reviewbybees
> Schedule Templatized Jobs script.

- copy-move-diagnosis.groovy
Troubleshooting script to diagnose Move/Copy/Promote issue in a particular directory.
@reviewbybees
> Copy/Move/Promote diagnosis script.

- get-failed-alerts.groovy
Get the failed condition (Alerts) defined by the User or in the system
@reviewbybees
> Get Failed Alerts/Conditions script.

- create-shared-agent.groovy
> create a shared Agent JNLP from groovy

- deleteTemplateAssociation.groovy
> remove template association from a folder

- createPSEManagedMasterFromCode.groovy
@cloudbees/team-support @cloudbees/team-tiger
> create a manager master from groovy

- get-groups-cjoc-master.groovy
> list groups at top level on Master and CJOC

- get-build-information.groovy
With this script, you can get build information using groovy.
@reviewbybees
> Script to get build information

- messaging-dump-cluster-database-CJOC.groovy
- messaging-dump-local-database-CJE-and-CJOC.groovy
@reviewbybees 
@cloudbees/team-cjp
> Groovy scripts to dump local and cluster messaging databases information and master status

- list-credential.groovy
> List ID and Description of all credentials on a Jenkins Instance.

- shared-agent-report-online-busy.groovy
> script to report the status of shared agents

- addClientMasterPlus.groovy
> Create a new ClientMaster and connect it to CJOC

- pipeline-approval-scripts.groovy
> Approve scripts/signatures on In-process Script Approval

- mark-login-users.groovy
if you execute it daily you have the creation date of user
@reviewbybees  @cloudbees/team-support
> solution to mark login users

- createMesosTemplate.groovy
> configure Mesos Cloud from a groovy script

- deleteClienteMaster.groovy
@cloudbees/team-support @reviewbybees
> delete client master

- GroupsFromLDAP.groovy
> This script allow you to test a LDAP configuration from the Jenkins console

- messaging-dump-cluster-database-CJOC.groovy
- messaging-dump-local-database-CJE-and-CJOC.groovy
> Fix mixed comments on messaging scripts

- modifiedAnalyticsConfig.groovy
> change analytics config

- create-palace-template.groovy
@cloudbees/team-support @cloudbees/team-tiger
> create a palace template from groovy

- listEC2InstancesOnAccount.groovy
it helps to diagnose EC2 Plugin issues.
see also https://github.com/jenkinsci/jenkins-scripts/pull/98 for the list only EC2 templates instances.
@cloudbees/team-support
> List all EC2 instances owner by the Account configured on the EC2 Cloud configurationn

- auth-project-report.groovy
AuthorizationMatrix (rbac-report.groovy like) report
> AuthorizationMatrix permission report

- sharedConfigFileProviderConfig.groovy
@cloudbees/team-support Got the idea from @alexanderrtaylor  in https://cloudbees.zendesk.com/agent/tickets/52734
> System script to push config file provider configuration

- get-lastlogin-users.groovy
> list all real users and shows the lastLogin datetime

- RBAC_Example.groovy
> [CE-1289]: Adding new location for adding groups to Containers

- README.md
- create-group4template.groovy
I would like to propose a couple of spelling corrections.
> Propose small spelling corrections

- count-cjoc-json.groovy
- print-masters-plugins.groovy
- print-rbac-report.groovy
- sharedConfigFileProviderConfig.groovy
> [CE-1763] Fix scripts using MasterClusterOps

- create-shared-agent.groovy
@cloudbees/team-support @alexanderrtaylor
> [CE-1849] Fix the Launcher

- ProperlyStopRunningPipelines.groovy
Added a groovy script in order to properly stop a series of running pipelines in the proper way in order to not have pipelines in a bad state
> Adding pipeline killing script

- mark-login-users.groovy
Minor typo fix and rewording of description.
> Minor typo and rewording of mark-login.users.groovy

- createPSEManagedMasterFromCode.groovy
@cloudbees/team-support 
Adding content on notes based on [ZD-68176](https://cloudbees.zendesk.com/agent/tickets/67994)
> [ZD-68176]: Managed Master creation

- create-controlled-agent.groovy
> [CE-2412] Basic script to create a controlled agent

- audit-user-permissions.groovy
I need this for https://cloudbees.zendesk.com/agent/tickets/74105
I've adjusted it slightly to be compatible with RBAC and to include any authorities/groups from the security realm.
> script to audit user permissions & external groups

- ProperlyStopRunningPipelines.groovy
> [ProperlyStopRunningPipelines]: Adding description for reason to abort builds forcefully

- mark-login-users.groovy
* syntax error in line 19
* creationDate and lastLogin were swapped
* removed creationDate from the last 2 else if. It didn't make sense
* added some quality-life tabs
> dates swapped and other fixes

- ProperlyStopRunningPipelines.groovy
> [CE-2935] Improve script for aborting running pipelines.

- cleanupAgentWorkspacesForSpecificAgents.groovy
https://cloudbees.atlassian.net/browse/CE-2988
> CE-2988 - Script to clean up agent workspaces for specific agents

- Node-token-report.groovy
Added a script to grab all the tokens for a connected node and then see what folders they are associated with
> Adding folder token audit script

- bulk-update-node-owner-properties.groovy
https://cloudbees.atlassian.net/browse/CE-3559
> CE-3559 - Groovy to set the 'Node Owner Properties' on all agents

- createManagedMasterK8s.groovy
- createManagedMasterMesos.groovy
- createTeamMasterK8s.groovy
- createTeamMasterMesos.groovy
[CE-2062](https://cloudbees.atlassian.net/browse/CE-2062) Adding scripts that we used in support to help customers create master programmatically.
> [CE-2062] Scripts to create Managed / Team Masters

- TriggerRestrictionsAudit.groovy
Added a script to check all the trigger restrictions on all folders
> Adding Trigger restrictions auditing

- copyGrpsBetweenNodes.groovy
This script is an adaptation of the script that Allan created to perform the same operation on Folders. In this particular case we use the corresponding class NodeProxyGroupContainer
> Script to copy Groups and Roles assigned to a Node

- approve-pending-signatures.groovy
Tested version of the script for current version of the plugin.
> CE-3195 Script to approve all the  pending signatures

- create-controlled-folder.groovy
Not sure if this is needed; but, I had some issues using the original script with an agent which was already created.
> Adding a variation of the create-controlled-agent script

- cleanupIdleFlyweightExecutor.groovy
[CE-3908](https://cloudbees.atlassian.net/browse/CE-3908) This script can be used as a workaround for https://issues.jenkins-ci.org/browse/JENKINS-57304
> [CE-3908] Add a script to remove idle flyweight executors

- JenkinsSharedSSHAgent
This Script will create a SSHSharedAgent on Jenkins
> Creates a SSHSharedAgent

- license-upgrade/apply-license.groovy
- license-upgrade/upgrade-license-plugin.groovy
- license-upgrade/verify-system-readiness.groovy
> documentation improvement

- license-upgrade/apply-license.groovy
> remove stage license server now that prod can generate licenses with the

- license-upgrade/apply-license.groovy
- license-upgrade/upgrade-license-plugin.groovy
- license-upgrade/verify-system-readiness.groovy
Better CJD discovery
Incrementals in 2.46.x.x
upstream of #130
> Beekeeper 2.46

- license-upgrade/verify-system-readiness.groovy
Manage properly masters with slow connections
> License master performance

- license-upgrade/apply-license.groovy
NullPointerException is thrown if the connected master doesn't reply in 20 seconds.
> Add timeout to apply license

- license-upgrade/apply-license.groovy
- license-upgrade/upgrade-license-plugin.groovy
- license-upgrade/verify-system-readiness.groovy
add script versioning to output
fix index OOB error
> SECO-412 - Index OOB error

- license-upgrade/apply-license.groovy
- license-upgrade/upgrade-license-plugin.groovy
- license-upgrade/verify-system-readiness.groovy
sometimes execute script returns empty status, probably because of a performance issue.
> Empty status is not allowed

- license-upgrade/apply-license.groovy
- license-upgrade/upgrade-license-plugin.groovy
- license-upgrade/verify-system-readiness.groovy
@ronniezhou asks for a fix at #131
> Fixed cloudbees-folders-plus typo

- license-upgrade/verify-system-readiness.groovy
> License verify only status

- license-upgrade/verify-cluster.sh
Recommended for huge clusters.
Probably more testing required...
> Bash script version

- findAllViewsWithGroupsDefined.groovy
[CTR-2704](https://cloudbees.atlassian.net/browse/CTR-2704)
Groovy script to run on a master which shows what views have RBAC groups
defined on them
> [CTR-2704] add a script to find all views that have groups defined

- rbacOnItems.groovy
We retrieve information about external groups, idStrategy (user and group), global groups, and groups on items:
```
{
"external": {
"groups": [
{
"ship_crew": [
"Bender Bending Rodr\u00edguez",
"Turanga Leela",
"Philip J. Fry"
]
},
{
"admin_staff": [
"Hubert J. Farnsworth",
"Hermes Conrad",
"Emilio Escobar"
]
}
],
"users": [
{
"professor": [
"admin_staff"
]
},
{
"emilio": [
"admin_staff"
]
},
{
"fry": [
"ship_crew"
]
}
]
},
"userIdStrategy": "jenkins.model.IdStrategy$CaseInsensitive",
"groups": [
{
"roles": [
"administrator"
],
"members": [
{
"kind": "external",
"name": "admin_staff"
}
],
"name": "Administrators"
}
],
"groupIdStrategy": "jenkins.model.IdStrategy$CaseInsensitive",
"items": [
{
"kind": "com.cloudbees.hudson.plugins.folder.Folder",
"name": "development",
"fullName": …
```
> Reports information about rbac on items

- identifyAvailableParameters.groovy
Identify details about job parameters
> [CE-5536] Quick script to get available job parameter details

- identifyAvailablePermissions.groovy
List available permissions and their description
> [CE-5537] Quick script to get available permissions and their description

- list-credential.groovy
https://github.com/jenkinsci/credentials-plugin/blob/master/src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java#L1277
> CE-5879: adding fingerprinting to the credential list

- rbac-report.groovy
This change is meant to fix a problem pending fixing in the nectar-rbac plugin BEE-727.
> Change to workaround BEE-727

- createManagedMasterK8s.groovy
https://cloudbees.atlassian.net/browse/BEE-2666 (May release)
> [BEE-2666] create the managed controller with the configuration bundle

- createManagedMasterK8s.groovy
> Forces the value of the token

- createManagedMasterK8s.groovy
- createTeamMasterK8s.groovy
- pom.xml
* Controllers must be associated at controller level since version 2.277.4.x. 
* `ConnectedMasterTokenProperty` is required since version 2.289.1.2.
> [CE-6163] Provide information about CasC compatibility

- createManagedMasterK8s.groovy
* Master is replaced with Controller where possible;
* An option to create Controller in a Folder is added.
> Managed Controller creation script is refreshed

- listControlledAgentsFolders.groovy
[CE-6290](https://cloudbees.atlassian.net/browse/CE-6290)
> [CE-6290] Add a script to list controlled agents' folders

- pom.xml
- rbac-report.groovy
Before printing the groups of the container, print the roles that are filtered out and require explicit assignment.
> CE-6560 - Print the roles that are filtered in the rbac report

- setOrgFolderIndex.groovy
Minor improvement to make it clearer to Groovy novices how they can use this script to change the indexing interval.
> Clarify usage of setOrgFolderIndex.groovy

- UpdateLivenessReadiness.groovy
Not sure if we should share it with customers though
> Groovy to update Liveness and readiness values

- restart-tcpagentlistener.groovy
> Relaunch TcpAgentListener thread
